language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
    - sh -c "sudo mkdir vendor"
    - sh -c "sudo mount -t tmpfs -o size=512M tmpfs vendor"

install:
    - composer install --prefer-source --no-interaction

script:
  - phpunit